#!/bin/sh
set -e -u -o pipefail

cd /app/ovpn/config/windscribe

if [ -n "$VPNHOST" -a -n "$VPNPORT" ]; then
  sed -i "s/VPNHOST/$VPNHOST/" client.conf
  sed -i "s/VPNPORT/$VPNPORT/" client.conf
  chmod 644 client.conf
  set -- "$@" '--config' 'client.conf'
else
  echo "OpenVPN server and/or port not set. Exiting."
  exit 1
fi

# Disable IPv6 if set.
if [ ! -z ${DISABLE_IPV6+x} ]; then
  echo 'pull-filter ignore "ifconfig-ipv6 "' >> client.conf
  echo 'pull-filter ignore "route-ipv6 "' >> client.conf
  sed -i "s/proto udp$/proto udp4/" client.conf
fi

if [ -n "$USERNAME" -a -n "$PASSWORD" ]; then
  echo "$USERNAME" > auth.conf
  echo "$PASSWORD" >> auth.conf
  chmod 600 auth.conf
  set -- "$@" '--auth-user-pass' 'auth.conf'
else
  echo "OpenVPN credentials not set. Exiting."
  exit 1
fi

openvpn "$@"
